//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploidutempsWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cours
    {
        public int idCours { get; set; }
        public string heuredebut { get; set; }
        public string heurefin { get; set; }
        public string jour { get; set; }
        public string professeur { get; set; }
        public string salle { get; set; }
        public string matiere { get; set; }
    }
}
