//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploidutempsWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Presence
    {
        public int idPresence { get; set; }
        public int idCours { get; set; }
        public int idUtilisateurs { get; set; }
    }
}
